spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        default_schema:
#  aws:
#    secretsmanager:
#      region: us-east-1
#      secretName: Backend-to-db
#      endpoint: secretsmanager.us-east-1.amazonaws.com
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: org.postgresql.Driver
#database-2.cetevaxypiv0.us-east-1.rds.amazonaws.com